theme: jekyll-theme-minimal
title: Secretish Squirrel's Secret Stash
description: A stash of Cybersecurity Labs, Lectures and Other Materials. Resources created by [Rich Macfarlane](https://twitter.com/rjmacfarlane)
logo: squirrel.png
